WITH base AS (
    SELECT
        gp.game_id,
        gp.a1, gp.a2, gp.a3, gp.a4, gp.a5,
        gp.h1, gp.h2, gp.h3, gp.h4, gp.h5,
        gp.net_pts,
        gp.poss,
        gp.net_eff,
        gp.lineup_id,
        CAST(g.game_date AS DATE) AS game_date,
        CAST(CAST(g.game_date AS DATE) - INTERVAL '1' DAY AS DATE) AS stats_date
    FROM grouped_possessions gp
    JOIN games g ON gp.game_id = g.game_id
    WHERE gp.poss >= 10
),

away_expanded AS (
    SELECT
        b.game_id, b.lineup_id, b.net_pts, b.poss, b.net_eff, b.game_date, b.stats_date,
        CAST(unnest([b.a1, b.a2, b.a3, b.a4, b.a5]) AS BIGINT) AS player_id
    FROM base b
),

away_ranked AS (
    SELECT
        ae.game_id, ae.lineup_id, ae.net_pts, ae.poss, ae.net_eff, ae.game_date,
        ae.player_id,
        s.team,
        s.conf,
        s.gp,
        s.min_pct,
        s.ortg,
        s.usg,
        s.efg,
        s.ts,
        s.orb,
        s.drb,
        s.ast,
        s.tov,
        s.ftm,
        s.fta,
        s.ft_pct,
        s.two_pm,
        s.two_pa,
        s.two_p_pct,
        s.tpm,
        s.tpa,
        s.tp_pct,
        s.blk,
        s.stl,
        s.ftr,
        s.yr,
        s.ht,
        s.num,
        s.porpag,
        s.adjoe,
        s.pfr,
        s.season_year,
        s.pid,
        s.type,
        s.rec_rank,
        s.ast_tov,
        s.rim_made,
        s.rim_att,
        s.mid_made,
        s.mid_att,
        s.rim_pct,
        s.mid_pct,
        s.dunks_made,
        s.dunks_att,
        s.dunk_pct,
        s.pick,
        s.drtg,
        s.adrtg,
        s.dporpag,
        s.stops,
        s.bpm,
        s.obpm,
        s.dbpm,
        s.gbpm,
        s.mp,
        s.ogbpm,
        s.dgbpm,
        s.oreb,
        s.dreb,
        s.treb,
        s.ast_raw,
        s.stl_raw,
        s.blk_raw,
        s.pts,
        s.role,
        s.three_p_100,
        s.player_name,
        ROW_NUMBER() OVER ( PARTITION BY ae.game_id, ae.lineup_id ORDER BY COALESCE(CAST(s.usg AS DOUBLE), 0) DESC) AS rn
    FROM away_expanded ae
    LEFT JOIN stats s
        ON ae.player_id = s.espn_player_id
       AND CAST(s.date AS DATE) = ae.stats_date
),

away_pivoted AS (
    SELECT
        game_id, lineup_id,
        MAX(net_pts)   AS net_pts,
        MAX(poss)      AS poss,
        MAX(net_eff)   AS net_eff,
        MAX(game_date) AS game_date,
        MAX(CASE WHEN rn = 1 THEN player_id END) AS a1_player_id,
        MAX(CASE WHEN rn = 1 THEN player_name END) AS a1_player_name,
        MAX(CASE WHEN rn = 1 THEN team END) AS a1_team,
        MAX(CASE WHEN rn = 1 THEN conf END) AS a1_conf,
        MAX(CASE WHEN rn = 1 THEN gp END) AS a1_gp,
        MAX(CASE WHEN rn = 1 THEN min_pct END) AS a1_min_pct,
        MAX(CASE WHEN rn = 1 THEN ortg END) AS a1_ortg,
        MAX(CASE WHEN rn = 1 THEN usg END) AS a1_usg,
        MAX(CASE WHEN rn = 1 THEN efg END) AS a1_efg,
        MAX(CASE WHEN rn = 1 THEN ts END) AS a1_ts,
        MAX(CASE WHEN rn = 1 THEN orb END) AS a1_orb,
        MAX(CASE WHEN rn = 1 THEN drb END) AS a1_drb,
        MAX(CASE WHEN rn = 1 THEN ast END) AS a1_ast,
        MAX(CASE WHEN rn = 1 THEN tov END) AS a1_tov,
        MAX(CASE WHEN rn = 1 THEN ftm END) AS a1_ftm,
        MAX(CASE WHEN rn = 1 THEN fta END) AS a1_fta,
        MAX(CASE WHEN rn = 1 THEN ft_pct END) AS a1_ft_pct,
        MAX(CASE WHEN rn = 1 THEN two_pm END) AS a1_two_pm,
        MAX(CASE WHEN rn = 1 THEN two_pa END) AS a1_two_pa,
        MAX(CASE WHEN rn = 1 THEN two_p_pct END) AS a1_two_p_pct,
        MAX(CASE WHEN rn = 1 THEN tpm END) AS a1_tpm,
        MAX(CASE WHEN rn = 1 THEN tpa END) AS a1_tpa,
        MAX(CASE WHEN rn = 1 THEN tp_pct END) AS a1_tp_pct,
        MAX(CASE WHEN rn = 1 THEN blk END) AS a1_blk,
        MAX(CASE WHEN rn = 1 THEN stl END) AS a1_stl,
        MAX(CASE WHEN rn = 1 THEN ftr END) AS a1_ftr,
        MAX(CASE WHEN rn = 1 THEN yr END) AS a1_yr,
        MAX(CASE WHEN rn = 1 THEN ht END) AS a1_ht,
        MAX(CASE WHEN rn = 1 THEN num END) AS a1_num,
        MAX(CASE WHEN rn = 1 THEN porpag END) AS a1_porpag,
        MAX(CASE WHEN rn = 1 THEN adjoe END) AS a1_adjoe,
        MAX(CASE WHEN rn = 1 THEN pfr END) AS a1_pfr,
        MAX(CASE WHEN rn = 1 THEN season_year END) AS a1_season_year,
        MAX(CASE WHEN rn = 1 THEN pid END) AS a1_pid,
        MAX(CASE WHEN rn = 1 THEN type END) AS a1_type,
        MAX(CASE WHEN rn = 1 THEN rec_rank END) AS a1_rec_rank,
        MAX(CASE WHEN rn = 1 THEN ast_tov END) AS a1_ast_tov,
        MAX(CASE WHEN rn = 1 THEN rim_made END) AS a1_rim_made,
        MAX(CASE WHEN rn = 1 THEN rim_att END) AS a1_rim_att,
        MAX(CASE WHEN rn = 1 THEN mid_made END) AS a1_mid_made,
        MAX(CASE WHEN rn = 1 THEN mid_att END) AS a1_mid_att,
        MAX(CASE WHEN rn = 1 THEN rim_pct END) AS a1_rim_pct,
        MAX(CASE WHEN rn = 1 THEN mid_pct END) AS a1_mid_pct,
        MAX(CASE WHEN rn = 1 THEN dunks_made END) AS a1_dunks_made,
        MAX(CASE WHEN rn = 1 THEN dunks_att END) AS a1_dunks_att,
        MAX(CASE WHEN rn = 1 THEN dunk_pct END) AS a1_dunk_pct,
        MAX(CASE WHEN rn = 1 THEN pick END) AS a1_pick,
        MAX(CASE WHEN rn = 1 THEN drtg END) AS a1_drtg,
        MAX(CASE WHEN rn = 1 THEN adrtg END) AS a1_adrtg,
        MAX(CASE WHEN rn = 1 THEN dporpag END) AS a1_dporpag,
        MAX(CASE WHEN rn = 1 THEN stops END) AS a1_stops,
        MAX(CASE WHEN rn = 1 THEN bpm END) AS a1_bpm,
        MAX(CASE WHEN rn = 1 THEN obpm END) AS a1_obpm,
        MAX(CASE WHEN rn = 1 THEN dbpm END) AS a1_dbpm,
        MAX(CASE WHEN rn = 1 THEN gbpm END) AS a1_gbpm,
        MAX(CASE WHEN rn = 1 THEN mp END) AS a1_mp,
        MAX(CASE WHEN rn = 1 THEN ogbpm END) AS a1_ogbpm,
        MAX(CASE WHEN rn = 1 THEN dgbpm END) AS a1_dgbpm,
        MAX(CASE WHEN rn = 1 THEN oreb END) AS a1_oreb,
        MAX(CASE WHEN rn = 1 THEN dreb END) AS a1_dreb,
        MAX(CASE WHEN rn = 1 THEN treb END) AS a1_treb,
        MAX(CASE WHEN rn = 1 THEN ast_raw END) AS a1_ast_raw,
        MAX(CASE WHEN rn = 1 THEN stl_raw END) AS a1_stl_raw,
        MAX(CASE WHEN rn = 1 THEN blk_raw END) AS a1_blk_raw,
        MAX(CASE WHEN rn = 1 THEN pts END) AS a1_pts,
        MAX(CASE WHEN rn = 1 THEN role END) AS a1_role,
        MAX(CASE WHEN rn = 1 THEN three_p_100 END) AS a1_three_p_100,
        MAX(CASE WHEN rn = 2 THEN player_id END) AS a2_player_id,
        MAX(CASE WHEN rn = 2 THEN player_name END) AS a2_player_name,
        MAX(CASE WHEN rn = 2 THEN team END) AS a2_team,
        MAX(CASE WHEN rn = 2 THEN conf END) AS a2_conf,
        MAX(CASE WHEN rn = 2 THEN gp END) AS a2_gp,
        MAX(CASE WHEN rn = 2 THEN min_pct END) AS a2_min_pct,
        MAX(CASE WHEN rn = 2 THEN ortg END) AS a2_ortg,
        MAX(CASE WHEN rn = 2 THEN usg END) AS a2_usg,
        MAX(CASE WHEN rn = 2 THEN efg END) AS a2_efg,
        MAX(CASE WHEN rn = 2 THEN ts END) AS a2_ts,
        MAX(CASE WHEN rn = 2 THEN orb END) AS a2_orb,
        MAX(CASE WHEN rn = 2 THEN drb END) AS a2_drb,
        MAX(CASE WHEN rn = 2 THEN ast END) AS a2_ast,
        MAX(CASE WHEN rn = 2 THEN tov END) AS a2_tov,
        MAX(CASE WHEN rn = 2 THEN ftm END) AS a2_ftm,
        MAX(CASE WHEN rn = 2 THEN fta END) AS a2_fta,
        MAX(CASE WHEN rn = 2 THEN ft_pct END) AS a2_ft_pct,
        MAX(CASE WHEN rn = 2 THEN two_pm END) AS a2_two_pm,
        MAX(CASE WHEN rn = 2 THEN two_pa END) AS a2_two_pa,
        MAX(CASE WHEN rn = 2 THEN two_p_pct END) AS a2_two_p_pct,
        MAX(CASE WHEN rn = 2 THEN tpm END) AS a2_tpm,
        MAX(CASE WHEN rn = 2 THEN tpa END) AS a2_tpa,
        MAX(CASE WHEN rn = 2 THEN tp_pct END) AS a2_tp_pct,
        MAX(CASE WHEN rn = 2 THEN blk END) AS a2_blk,
        MAX(CASE WHEN rn = 2 THEN stl END) AS a2_stl,
        MAX(CASE WHEN rn = 2 THEN ftr END) AS a2_ftr,
        MAX(CASE WHEN rn = 2 THEN yr END) AS a2_yr,
        MAX(CASE WHEN rn = 2 THEN ht END) AS a2_ht,
        MAX(CASE WHEN rn = 2 THEN num END) AS a2_num,
        MAX(CASE WHEN rn = 2 THEN porpag END) AS a2_porpag,
        MAX(CASE WHEN rn = 2 THEN adjoe END) AS a2_adjoe,
        MAX(CASE WHEN rn = 2 THEN pfr END) AS a2_pfr,
        MAX(CASE WHEN rn = 2 THEN season_year END) AS a2_season_year,
        MAX(CASE WHEN rn = 2 THEN pid END) AS a2_pid,
        MAX(CASE WHEN rn = 2 THEN type END) AS a2_type,
        MAX(CASE WHEN rn = 2 THEN rec_rank END) AS a2_rec_rank,
        MAX(CASE WHEN rn = 2 THEN ast_tov END) AS a2_ast_tov,
        MAX(CASE WHEN rn = 2 THEN rim_made END) AS a2_rim_made,
        MAX(CASE WHEN rn = 2 THEN rim_att END) AS a2_rim_att,
        MAX(CASE WHEN rn = 2 THEN mid_made END) AS a2_mid_made,
        MAX(CASE WHEN rn = 2 THEN mid_att END) AS a2_mid_att,
        MAX(CASE WHEN rn = 2 THEN rim_pct END) AS a2_rim_pct,
        MAX(CASE WHEN rn = 2 THEN mid_pct END) AS a2_mid_pct,
        MAX(CASE WHEN rn = 2 THEN dunks_made END) AS a2_dunks_made,
        MAX(CASE WHEN rn = 2 THEN dunks_att END) AS a2_dunks_att,
        MAX(CASE WHEN rn = 2 THEN dunk_pct END) AS a2_dunk_pct,
        MAX(CASE WHEN rn = 2 THEN pick END) AS a2_pick,
        MAX(CASE WHEN rn = 2 THEN drtg END) AS a2_drtg,
        MAX(CASE WHEN rn = 2 THEN adrtg END) AS a2_adrtg,
        MAX(CASE WHEN rn = 2 THEN dporpag END) AS a2_dporpag,
        MAX(CASE WHEN rn = 2 THEN stops END) AS a2_stops,
        MAX(CASE WHEN rn = 2 THEN bpm END) AS a2_bpm,
        MAX(CASE WHEN rn = 2 THEN obpm END) AS a2_obpm,
        MAX(CASE WHEN rn = 2 THEN dbpm END) AS a2_dbpm,
        MAX(CASE WHEN rn = 2 THEN gbpm END) AS a2_gbpm,
        MAX(CASE WHEN rn = 2 THEN mp END) AS a2_mp,
        MAX(CASE WHEN rn = 2 THEN ogbpm END) AS a2_ogbpm,
        MAX(CASE WHEN rn = 2 THEN dgbpm END) AS a2_dgbpm,
        MAX(CASE WHEN rn = 2 THEN oreb END) AS a2_oreb,
        MAX(CASE WHEN rn = 2 THEN dreb END) AS a2_dreb,
        MAX(CASE WHEN rn = 2 THEN treb END) AS a2_treb,
        MAX(CASE WHEN rn = 2 THEN ast_raw END) AS a2_ast_raw,
        MAX(CASE WHEN rn = 2 THEN stl_raw END) AS a2_stl_raw,
        MAX(CASE WHEN rn = 2 THEN blk_raw END) AS a2_blk_raw,
        MAX(CASE WHEN rn = 2 THEN pts END) AS a2_pts,
        MAX(CASE WHEN rn = 2 THEN role END) AS a2_role,
        MAX(CASE WHEN rn = 2 THEN three_p_100 END) AS a2_three_p_100,
        MAX(CASE WHEN rn = 3 THEN player_id END) AS a3_player_id,
        MAX(CASE WHEN rn = 3 THEN player_name END) AS a3_player_name,
        MAX(CASE WHEN rn = 3 THEN team END) AS a3_team,
        MAX(CASE WHEN rn = 3 THEN conf END) AS a3_conf,
        MAX(CASE WHEN rn = 3 THEN gp END) AS a3_gp,
        MAX(CASE WHEN rn = 3 THEN min_pct END) AS a3_min_pct,
        MAX(CASE WHEN rn = 3 THEN ortg END) AS a3_ortg,
        MAX(CASE WHEN rn = 3 THEN usg END) AS a3_usg,
        MAX(CASE WHEN rn = 3 THEN efg END) AS a3_efg,
        MAX(CASE WHEN rn = 3 THEN ts END) AS a3_ts,
        MAX(CASE WHEN rn = 3 THEN orb END) AS a3_orb,
        MAX(CASE WHEN rn = 3 THEN drb END) AS a3_drb,
        MAX(CASE WHEN rn = 3 THEN ast END) AS a3_ast,
        MAX(CASE WHEN rn = 3 THEN tov END) AS a3_tov,
        MAX(CASE WHEN rn = 3 THEN ftm END) AS a3_ftm,
        MAX(CASE WHEN rn = 3 THEN fta END) AS a3_fta,
        MAX(CASE WHEN rn = 3 THEN ft_pct END) AS a3_ft_pct,
        MAX(CASE WHEN rn = 3 THEN two_pm END) AS a3_two_pm,
        MAX(CASE WHEN rn = 3 THEN two_pa END) AS a3_two_pa,
        MAX(CASE WHEN rn = 3 THEN two_p_pct END) AS a3_two_p_pct,
        MAX(CASE WHEN rn = 3 THEN tpm END) AS a3_tpm,
        MAX(CASE WHEN rn = 3 THEN tpa END) AS a3_tpa,
        MAX(CASE WHEN rn = 3 THEN tp_pct END) AS a3_tp_pct,
        MAX(CASE WHEN rn = 3 THEN blk END) AS a3_blk,
        MAX(CASE WHEN rn = 3 THEN stl END) AS a3_stl,
        MAX(CASE WHEN rn = 3 THEN ftr END) AS a3_ftr,
        MAX(CASE WHEN rn = 3 THEN yr END) AS a3_yr,
        MAX(CASE WHEN rn = 3 THEN ht END) AS a3_ht,
        MAX(CASE WHEN rn = 3 THEN num END) AS a3_num,
        MAX(CASE WHEN rn = 3 THEN porpag END) AS a3_porpag,
        MAX(CASE WHEN rn = 3 THEN adjoe END) AS a3_adjoe,
        MAX(CASE WHEN rn = 3 THEN pfr END) AS a3_pfr,
        MAX(CASE WHEN rn = 3 THEN season_year END) AS a3_season_year,
        MAX(CASE WHEN rn = 3 THEN pid END) AS a3_pid,
        MAX(CASE WHEN rn = 3 THEN type END) AS a3_type,
        MAX(CASE WHEN rn = 3 THEN rec_rank END) AS a3_rec_rank,
        MAX(CASE WHEN rn = 3 THEN ast_tov END) AS a3_ast_tov,
        MAX(CASE WHEN rn = 3 THEN rim_made END) AS a3_rim_made,
        MAX(CASE WHEN rn = 3 THEN rim_att END) AS a3_rim_att,
        MAX(CASE WHEN rn = 3 THEN mid_made END) AS a3_mid_made,
        MAX(CASE WHEN rn = 3 THEN mid_att END) AS a3_mid_att,
        MAX(CASE WHEN rn = 3 THEN rim_pct END) AS a3_rim_pct,
        MAX(CASE WHEN rn = 3 THEN mid_pct END) AS a3_mid_pct,
        MAX(CASE WHEN rn = 3 THEN dunks_made END) AS a3_dunks_made,
        MAX(CASE WHEN rn = 3 THEN dunks_att END) AS a3_dunks_att,
        MAX(CASE WHEN rn = 3 THEN dunk_pct END) AS a3_dunk_pct,
        MAX(CASE WHEN rn = 3 THEN pick END) AS a3_pick,
        MAX(CASE WHEN rn = 3 THEN drtg END) AS a3_drtg,
        MAX(CASE WHEN rn = 3 THEN adrtg END) AS a3_adrtg,
        MAX(CASE WHEN rn = 3 THEN dporpag END) AS a3_dporpag,
        MAX(CASE WHEN rn = 3 THEN stops END) AS a3_stops,
        MAX(CASE WHEN rn = 3 THEN bpm END) AS a3_bpm,
        MAX(CASE WHEN rn = 3 THEN obpm END) AS a3_obpm,
        MAX(CASE WHEN rn = 3 THEN dbpm END) AS a3_dbpm,
        MAX(CASE WHEN rn = 3 THEN gbpm END) AS a3_gbpm,
        MAX(CASE WHEN rn = 3 THEN mp END) AS a3_mp,
        MAX(CASE WHEN rn = 3 THEN ogbpm END) AS a3_ogbpm,
        MAX(CASE WHEN rn = 3 THEN dgbpm END) AS a3_dgbpm,
        MAX(CASE WHEN rn = 3 THEN oreb END) AS a3_oreb,
        MAX(CASE WHEN rn = 3 THEN dreb END) AS a3_dreb,
        MAX(CASE WHEN rn = 3 THEN treb END) AS a3_treb,
        MAX(CASE WHEN rn = 3 THEN ast_raw END) AS a3_ast_raw,
        MAX(CASE WHEN rn = 3 THEN stl_raw END) AS a3_stl_raw,
        MAX(CASE WHEN rn = 3 THEN blk_raw END) AS a3_blk_raw,
        MAX(CASE WHEN rn = 3 THEN pts END) AS a3_pts,
        MAX(CASE WHEN rn = 3 THEN role END) AS a3_role,
        MAX(CASE WHEN rn = 3 THEN three_p_100 END) AS a3_three_p_100,
        MAX(CASE WHEN rn = 4 THEN player_id END) AS a4_player_id,
        MAX(CASE WHEN rn = 4 THEN player_name END) AS a4_player_name,
        MAX(CASE WHEN rn = 4 THEN team END) AS a4_team,
        MAX(CASE WHEN rn = 4 THEN conf END) AS a4_conf,
        MAX(CASE WHEN rn = 4 THEN gp END) AS a4_gp,
        MAX(CASE WHEN rn = 4 THEN min_pct END) AS a4_min_pct,
        MAX(CASE WHEN rn = 4 THEN ortg END) AS a4_ortg,
        MAX(CASE WHEN rn = 4 THEN usg END) AS a4_usg,
        MAX(CASE WHEN rn = 4 THEN efg END) AS a4_efg,
        MAX(CASE WHEN rn = 4 THEN ts END) AS a4_ts,
        MAX(CASE WHEN rn = 4 THEN orb END) AS a4_orb,
        MAX(CASE WHEN rn = 4 THEN drb END) AS a4_drb,
        MAX(CASE WHEN rn = 4 THEN ast END) AS a4_ast,
        MAX(CASE WHEN rn = 4 THEN tov END) AS a4_tov,
        MAX(CASE WHEN rn = 4 THEN ftm END) AS a4_ftm,
        MAX(CASE WHEN rn = 4 THEN fta END) AS a4_fta,
        MAX(CASE WHEN rn = 4 THEN ft_pct END) AS a4_ft_pct,
        MAX(CASE WHEN rn = 4 THEN two_pm END) AS a4_two_pm,
        MAX(CASE WHEN rn = 4 THEN two_pa END) AS a4_two_pa,
        MAX(CASE WHEN rn = 4 THEN two_p_pct END) AS a4_two_p_pct,
        MAX(CASE WHEN rn = 4 THEN tpm END) AS a4_tpm,
        MAX(CASE WHEN rn = 4 THEN tpa END) AS a4_tpa,
        MAX(CASE WHEN rn = 4 THEN tp_pct END) AS a4_tp_pct,
        MAX(CASE WHEN rn = 4 THEN blk END) AS a4_blk,
        MAX(CASE WHEN rn = 4 THEN stl END) AS a4_stl,
        MAX(CASE WHEN rn = 4 THEN ftr END) AS a4_ftr,
        MAX(CASE WHEN rn = 4 THEN yr END) AS a4_yr,
        MAX(CASE WHEN rn = 4 THEN ht END) AS a4_ht,
        MAX(CASE WHEN rn = 4 THEN num END) AS a4_num,
        MAX(CASE WHEN rn = 4 THEN porpag END) AS a4_porpag,
        MAX(CASE WHEN rn = 4 THEN adjoe END) AS a4_adjoe,
        MAX(CASE WHEN rn = 4 THEN pfr END) AS a4_pfr,
        MAX(CASE WHEN rn = 4 THEN season_year END) AS a4_season_year,
        MAX(CASE WHEN rn = 4 THEN pid END) AS a4_pid,
        MAX(CASE WHEN rn = 4 THEN type END) AS a4_type,
        MAX(CASE WHEN rn = 4 THEN rec_rank END) AS a4_rec_rank,
        MAX(CASE WHEN rn = 4 THEN ast_tov END) AS a4_ast_tov,
        MAX(CASE WHEN rn = 4 THEN rim_made END) AS a4_rim_made,
        MAX(CASE WHEN rn = 4 THEN rim_att END) AS a4_rim_att,
        MAX(CASE WHEN rn = 4 THEN mid_made END) AS a4_mid_made,
        MAX(CASE WHEN rn = 4 THEN mid_att END) AS a4_mid_att,
        MAX(CASE WHEN rn = 4 THEN rim_pct END) AS a4_rim_pct,
        MAX(CASE WHEN rn = 4 THEN mid_pct END) AS a4_mid_pct,
        MAX(CASE WHEN rn = 4 THEN dunks_made END) AS a4_dunks_made,
        MAX(CASE WHEN rn = 4 THEN dunks_att END) AS a4_dunks_att,
        MAX(CASE WHEN rn = 4 THEN dunk_pct END) AS a4_dunk_pct,
        MAX(CASE WHEN rn = 4 THEN pick END) AS a4_pick,
        MAX(CASE WHEN rn = 4 THEN drtg END) AS a4_drtg,
        MAX(CASE WHEN rn = 4 THEN adrtg END) AS a4_adrtg,
        MAX(CASE WHEN rn = 4 THEN dporpag END) AS a4_dporpag,
        MAX(CASE WHEN rn = 4 THEN stops END) AS a4_stops,
        MAX(CASE WHEN rn = 4 THEN bpm END) AS a4_bpm,
        MAX(CASE WHEN rn = 4 THEN obpm END) AS a4_obpm,
        MAX(CASE WHEN rn = 4 THEN dbpm END) AS a4_dbpm,
        MAX(CASE WHEN rn = 4 THEN gbpm END) AS a4_gbpm,
        MAX(CASE WHEN rn = 4 THEN mp END) AS a4_mp,
        MAX(CASE WHEN rn = 4 THEN ogbpm END) AS a4_ogbpm,
        MAX(CASE WHEN rn = 4 THEN dgbpm END) AS a4_dgbpm,
        MAX(CASE WHEN rn = 4 THEN oreb END) AS a4_oreb,
        MAX(CASE WHEN rn = 4 THEN dreb END) AS a4_dreb,
        MAX(CASE WHEN rn = 4 THEN treb END) AS a4_treb,
        MAX(CASE WHEN rn = 4 THEN ast_raw END) AS a4_ast_raw,
        MAX(CASE WHEN rn = 4 THEN stl_raw END) AS a4_stl_raw,
        MAX(CASE WHEN rn = 4 THEN blk_raw END) AS a4_blk_raw,
        MAX(CASE WHEN rn = 4 THEN pts END) AS a4_pts,
        MAX(CASE WHEN rn = 4 THEN role END) AS a4_role,
        MAX(CASE WHEN rn = 4 THEN three_p_100 END) AS a4_three_p_100,
        MAX(CASE WHEN rn = 5 THEN player_id END) AS a5_player_id,
        MAX(CASE WHEN rn = 5 THEN player_name END) AS a5_player_name,
        MAX(CASE WHEN rn = 5 THEN team END) AS a5_team,
        MAX(CASE WHEN rn = 5 THEN conf END) AS a5_conf,
        MAX(CASE WHEN rn = 5 THEN gp END) AS a5_gp,
        MAX(CASE WHEN rn = 5 THEN min_pct END) AS a5_min_pct,
        MAX(CASE WHEN rn = 5 THEN ortg END) AS a5_ortg,
        MAX(CASE WHEN rn = 5 THEN usg END) AS a5_usg,
        MAX(CASE WHEN rn = 5 THEN efg END) AS a5_efg,
        MAX(CASE WHEN rn = 5 THEN ts END) AS a5_ts,
        MAX(CASE WHEN rn = 5 THEN orb END) AS a5_orb,
        MAX(CASE WHEN rn = 5 THEN drb END) AS a5_drb,
        MAX(CASE WHEN rn = 5 THEN ast END) AS a5_ast,
        MAX(CASE WHEN rn = 5 THEN tov END) AS a5_tov,
        MAX(CASE WHEN rn = 5 THEN ftm END) AS a5_ftm,
        MAX(CASE WHEN rn = 5 THEN fta END) AS a5_fta,
        MAX(CASE WHEN rn = 5 THEN ft_pct END) AS a5_ft_pct,
        MAX(CASE WHEN rn = 5 THEN two_pm END) AS a5_two_pm,
        MAX(CASE WHEN rn = 5 THEN two_pa END) AS a5_two_pa,
        MAX(CASE WHEN rn = 5 THEN two_p_pct END) AS a5_two_p_pct,
        MAX(CASE WHEN rn = 5 THEN tpm END) AS a5_tpm,
        MAX(CASE WHEN rn = 5 THEN tpa END) AS a5_tpa,
        MAX(CASE WHEN rn = 5 THEN tp_pct END) AS a5_tp_pct,
        MAX(CASE WHEN rn = 5 THEN blk END) AS a5_blk,
        MAX(CASE WHEN rn = 5 THEN stl END) AS a5_stl,
        MAX(CASE WHEN rn = 5 THEN ftr END) AS a5_ftr,
        MAX(CASE WHEN rn = 5 THEN yr END) AS a5_yr,
        MAX(CASE WHEN rn = 5 THEN ht END) AS a5_ht,
        MAX(CASE WHEN rn = 5 THEN num END) AS a5_num,
        MAX(CASE WHEN rn = 5 THEN porpag END) AS a5_porpag,
        MAX(CASE WHEN rn = 5 THEN adjoe END) AS a5_adjoe,
        MAX(CASE WHEN rn = 5 THEN pfr END) AS a5_pfr,
        MAX(CASE WHEN rn = 5 THEN season_year END) AS a5_season_year,
        MAX(CASE WHEN rn = 5 THEN pid END) AS a5_pid,
        MAX(CASE WHEN rn = 5 THEN type END) AS a5_type,
        MAX(CASE WHEN rn = 5 THEN rec_rank END) AS a5_rec_rank,
        MAX(CASE WHEN rn = 5 THEN ast_tov END) AS a5_ast_tov,
        MAX(CASE WHEN rn = 5 THEN rim_made END) AS a5_rim_made,
        MAX(CASE WHEN rn = 5 THEN rim_att END) AS a5_rim_att,
        MAX(CASE WHEN rn = 5 THEN mid_made END) AS a5_mid_made,
        MAX(CASE WHEN rn = 5 THEN mid_att END) AS a5_mid_att,
        MAX(CASE WHEN rn = 5 THEN rim_pct END) AS a5_rim_pct,
        MAX(CASE WHEN rn = 5 THEN mid_pct END) AS a5_mid_pct,
        MAX(CASE WHEN rn = 5 THEN dunks_made END) AS a5_dunks_made,
        MAX(CASE WHEN rn = 5 THEN dunks_att END) AS a5_dunks_att,
        MAX(CASE WHEN rn = 5 THEN dunk_pct END) AS a5_dunk_pct,
        MAX(CASE WHEN rn = 5 THEN pick END) AS a5_pick,
        MAX(CASE WHEN rn = 5 THEN drtg END) AS a5_drtg,
        MAX(CASE WHEN rn = 5 THEN adrtg END) AS a5_adrtg,
        MAX(CASE WHEN rn = 5 THEN dporpag END) AS a5_dporpag,
        MAX(CASE WHEN rn = 5 THEN stops END) AS a5_stops,
        MAX(CASE WHEN rn = 5 THEN bpm END) AS a5_bpm,
        MAX(CASE WHEN rn = 5 THEN obpm END) AS a5_obpm,
        MAX(CASE WHEN rn = 5 THEN dbpm END) AS a5_dbpm,
        MAX(CASE WHEN rn = 5 THEN gbpm END) AS a5_gbpm,
        MAX(CASE WHEN rn = 5 THEN mp END) AS a5_mp,
        MAX(CASE WHEN rn = 5 THEN ogbpm END) AS a5_ogbpm,
        MAX(CASE WHEN rn = 5 THEN dgbpm END) AS a5_dgbpm,
        MAX(CASE WHEN rn = 5 THEN oreb END) AS a5_oreb,
        MAX(CASE WHEN rn = 5 THEN dreb END) AS a5_dreb,
        MAX(CASE WHEN rn = 5 THEN treb END) AS a5_treb,
        MAX(CASE WHEN rn = 5 THEN ast_raw END) AS a5_ast_raw,
        MAX(CASE WHEN rn = 5 THEN stl_raw END) AS a5_stl_raw,
        MAX(CASE WHEN rn = 5 THEN blk_raw END) AS a5_blk_raw,
        MAX(CASE WHEN rn = 5 THEN pts END) AS a5_pts,
        MAX(CASE WHEN rn = 5 THEN role END) AS a5_role,
        MAX(CASE WHEN rn = 5 THEN three_p_100 END) AS a5_three_p_100
    FROM away_ranked
    GROUP BY game_id, lineup_id
),

home_expanded AS (
    SELECT
        b.game_id, b.lineup_id, b.stats_date,
        CAST(unnest([b.h1, b.h2, b.h3, b.h4, b.h5]) AS BIGINT) AS player_id
    FROM base b
),

home_ranked AS (
    SELECT
        he.game_id, he.lineup_id,
        he.player_id,
        s.team,
        s.conf,
        s.gp,
        s.min_pct,
        s.ortg,
        s.usg,
        s.efg,
        s.ts,
        s.orb,
        s.drb,
        s.ast,
        s.tov,
        s.ftm,
        s.fta,
        s.ft_pct,
        s.two_pm,
        s.two_pa,
        s.two_p_pct,
        s.tpm,
        s.tpa,
        s.tp_pct,
        s.blk,
        s.stl,
        s.ftr,
        s.yr,
        s.ht,
        s.num,
        s.porpag,
        s.adjoe,
        s.pfr,
        s.season_year,
        s.pid,
        s.type,
        s.rec_rank,
        s.ast_tov,
        s.rim_made,
        s.rim_att,
        s.mid_made,
        s.mid_att,
        s.rim_pct,
        s.mid_pct,
        s.dunks_made,
        s.dunks_att,
        s.dunk_pct,
        s.pick,
        s.drtg,
        s.adrtg,
        s.dporpag,
        s.stops,
        s.bpm,
        s.obpm,
        s.dbpm,
        s.gbpm,
        s.mp,
        s.ogbpm,
        s.dgbpm,
        s.oreb,
        s.dreb,
        s.treb,
        s.ast_raw,
        s.stl_raw,
        s.blk_raw,
        s.pts,
        s.role,
        s.three_p_100,
        s.player_name,
        ROW_NUMBER() OVER (
            PARTITION BY he.game_id, he.lineup_id
            ORDER BY COALESCE(CAST(s.usg AS DOUBLE), 0) DESC
        ) AS rn
    FROM home_expanded he
    LEFT JOIN stats s
        ON he.player_id = s.espn_player_id
       AND CAST(s.date AS DATE) = he.stats_date
),

home_pivoted AS (
    SELECT
        game_id, lineup_id,
        MAX(CASE WHEN rn = 1 THEN player_id END) AS h1_player_id,
        MAX(CASE WHEN rn = 1 THEN player_name END) AS h1_player_name,
        MAX(CASE WHEN rn = 1 THEN team END) AS h1_team,
        MAX(CASE WHEN rn = 1 THEN conf END) AS h1_conf,
        MAX(CASE WHEN rn = 1 THEN gp END) AS h1_gp,
        MAX(CASE WHEN rn = 1 THEN min_pct END) AS h1_min_pct,
        MAX(CASE WHEN rn = 1 THEN ortg END) AS h1_ortg,
        MAX(CASE WHEN rn = 1 THEN usg END) AS h1_usg,
        MAX(CASE WHEN rn = 1 THEN efg END) AS h1_efg,
        MAX(CASE WHEN rn = 1 THEN ts END) AS h1_ts,
        MAX(CASE WHEN rn = 1 THEN orb END) AS h1_orb,
        MAX(CASE WHEN rn = 1 THEN drb END) AS h1_drb,
        MAX(CASE WHEN rn = 1 THEN ast END) AS h1_ast,
        MAX(CASE WHEN rn = 1 THEN tov END) AS h1_tov,
        MAX(CASE WHEN rn = 1 THEN ftm END) AS h1_ftm,
        MAX(CASE WHEN rn = 1 THEN fta END) AS h1_fta,
        MAX(CASE WHEN rn = 1 THEN ft_pct END) AS h1_ft_pct,
        MAX(CASE WHEN rn = 1 THEN two_pm END) AS h1_two_pm,
        MAX(CASE WHEN rn = 1 THEN two_pa END) AS h1_two_pa,
        MAX(CASE WHEN rn = 1 THEN two_p_pct END) AS h1_two_p_pct,
        MAX(CASE WHEN rn = 1 THEN tpm END) AS h1_tpm,
        MAX(CASE WHEN rn = 1 THEN tpa END) AS h1_tpa,
        MAX(CASE WHEN rn = 1 THEN tp_pct END) AS h1_tp_pct,
        MAX(CASE WHEN rn = 1 THEN blk END) AS h1_blk,
        MAX(CASE WHEN rn = 1 THEN stl END) AS h1_stl,
        MAX(CASE WHEN rn = 1 THEN ftr END) AS h1_ftr,
        MAX(CASE WHEN rn = 1 THEN yr END) AS h1_yr,
        MAX(CASE WHEN rn = 1 THEN ht END) AS h1_ht,
        MAX(CASE WHEN rn = 1 THEN num END) AS h1_num,
        MAX(CASE WHEN rn = 1 THEN porpag END) AS h1_porpag,
        MAX(CASE WHEN rn = 1 THEN adjoe END) AS h1_adjoe,
        MAX(CASE WHEN rn = 1 THEN pfr END) AS h1_pfr,
        MAX(CASE WHEN rn = 1 THEN season_year END) AS h1_season_year,
        MAX(CASE WHEN rn = 1 THEN pid END) AS h1_pid,
        MAX(CASE WHEN rn = 1 THEN type END) AS h1_type,
        MAX(CASE WHEN rn = 1 THEN rec_rank END) AS h1_rec_rank,
        MAX(CASE WHEN rn = 1 THEN ast_tov END) AS h1_ast_tov,
        MAX(CASE WHEN rn = 1 THEN rim_made END) AS h1_rim_made,
        MAX(CASE WHEN rn = 1 THEN rim_att END) AS h1_rim_att,
        MAX(CASE WHEN rn = 1 THEN mid_made END) AS h1_mid_made,
        MAX(CASE WHEN rn = 1 THEN mid_att END) AS h1_mid_att,
        MAX(CASE WHEN rn = 1 THEN rim_pct END) AS h1_rim_pct,
        MAX(CASE WHEN rn = 1 THEN mid_pct END) AS h1_mid_pct,
        MAX(CASE WHEN rn = 1 THEN dunks_made END) AS h1_dunks_made,
        MAX(CASE WHEN rn = 1 THEN dunks_att END) AS h1_dunks_att,
        MAX(CASE WHEN rn = 1 THEN dunk_pct END) AS h1_dunk_pct,
        MAX(CASE WHEN rn = 1 THEN pick END) AS h1_pick,
        MAX(CASE WHEN rn = 1 THEN drtg END) AS h1_drtg,
        MAX(CASE WHEN rn = 1 THEN adrtg END) AS h1_adrtg,
        MAX(CASE WHEN rn = 1 THEN dporpag END) AS h1_dporpag,
        MAX(CASE WHEN rn = 1 THEN stops END) AS h1_stops,
        MAX(CASE WHEN rn = 1 THEN bpm END) AS h1_bpm,
        MAX(CASE WHEN rn = 1 THEN obpm END) AS h1_obpm,
        MAX(CASE WHEN rn = 1 THEN dbpm END) AS h1_dbpm,
        MAX(CASE WHEN rn = 1 THEN gbpm END) AS h1_gbpm,
        MAX(CASE WHEN rn = 1 THEN mp END) AS h1_mp,
        MAX(CASE WHEN rn = 1 THEN ogbpm END) AS h1_ogbpm,
        MAX(CASE WHEN rn = 1 THEN dgbpm END) AS h1_dgbpm,
        MAX(CASE WHEN rn = 1 THEN oreb END) AS h1_oreb,
        MAX(CASE WHEN rn = 1 THEN dreb END) AS h1_dreb,
        MAX(CASE WHEN rn = 1 THEN treb END) AS h1_treb,
        MAX(CASE WHEN rn = 1 THEN ast_raw END) AS h1_ast_raw,
        MAX(CASE WHEN rn = 1 THEN stl_raw END) AS h1_stl_raw,
        MAX(CASE WHEN rn = 1 THEN blk_raw END) AS h1_blk_raw,
        MAX(CASE WHEN rn = 1 THEN pts END) AS h1_pts,
        MAX(CASE WHEN rn = 1 THEN role END) AS h1_role,
        MAX(CASE WHEN rn = 1 THEN three_p_100 END) AS h1_three_p_100,
        MAX(CASE WHEN rn = 2 THEN player_id END) AS h2_player_id,
        MAX(CASE WHEN rn = 2 THEN player_name END) AS h2_player_name,
        MAX(CASE WHEN rn = 2 THEN team END) AS h2_team,
        MAX(CASE WHEN rn = 2 THEN conf END) AS h2_conf,
        MAX(CASE WHEN rn = 2 THEN gp END) AS h2_gp,
        MAX(CASE WHEN rn = 2 THEN min_pct END) AS h2_min_pct,
        MAX(CASE WHEN rn = 2 THEN ortg END) AS h2_ortg,
        MAX(CASE WHEN rn = 2 THEN usg END) AS h2_usg,
        MAX(CASE WHEN rn = 2 THEN efg END) AS h2_efg,
        MAX(CASE WHEN rn = 2 THEN ts END) AS h2_ts,
        MAX(CASE WHEN rn = 2 THEN orb END) AS h2_orb,
        MAX(CASE WHEN rn = 2 THEN drb END) AS h2_drb,
        MAX(CASE WHEN rn = 2 THEN ast END) AS h2_ast,
        MAX(CASE WHEN rn = 2 THEN tov END) AS h2_tov,
        MAX(CASE WHEN rn = 2 THEN ftm END) AS h2_ftm,
        MAX(CASE WHEN rn = 2 THEN fta END) AS h2_fta,
        MAX(CASE WHEN rn = 2 THEN ft_pct END) AS h2_ft_pct,
        MAX(CASE WHEN rn = 2 THEN two_pm END) AS h2_two_pm,
        MAX(CASE WHEN rn = 2 THEN two_pa END) AS h2_two_pa,
        MAX(CASE WHEN rn = 2 THEN two_p_pct END) AS h2_two_p_pct,
        MAX(CASE WHEN rn = 2 THEN tpm END) AS h2_tpm,
        MAX(CASE WHEN rn = 2 THEN tpa END) AS h2_tpa,
        MAX(CASE WHEN rn = 2 THEN tp_pct END) AS h2_tp_pct,
        MAX(CASE WHEN rn = 2 THEN blk END) AS h2_blk,
        MAX(CASE WHEN rn = 2 THEN stl END) AS h2_stl,
        MAX(CASE WHEN rn = 2 THEN ftr END) AS h2_ftr,
        MAX(CASE WHEN rn = 2 THEN yr END) AS h2_yr,
        MAX(CASE WHEN rn = 2 THEN ht END) AS h2_ht,
        MAX(CASE WHEN rn = 2 THEN num END) AS h2_num,
        MAX(CASE WHEN rn = 2 THEN porpag END) AS h2_porpag,
        MAX(CASE WHEN rn = 2 THEN adjoe END) AS h2_adjoe,
        MAX(CASE WHEN rn = 2 THEN pfr END) AS h2_pfr,
        MAX(CASE WHEN rn = 2 THEN season_year END) AS h2_season_year,
        MAX(CASE WHEN rn = 2 THEN pid END) AS h2_pid,
        MAX(CASE WHEN rn = 2 THEN type END) AS h2_type,
        MAX(CASE WHEN rn = 2 THEN rec_rank END) AS h2_rec_rank,
        MAX(CASE WHEN rn = 2 THEN ast_tov END) AS h2_ast_tov,
        MAX(CASE WHEN rn = 2 THEN rim_made END) AS h2_rim_made,
        MAX(CASE WHEN rn = 2 THEN rim_att END) AS h2_rim_att,
        MAX(CASE WHEN rn = 2 THEN mid_made END) AS h2_mid_made,
        MAX(CASE WHEN rn = 2 THEN mid_att END) AS h2_mid_att,
        MAX(CASE WHEN rn = 2 THEN rim_pct END) AS h2_rim_pct,
        MAX(CASE WHEN rn = 2 THEN mid_pct END) AS h2_mid_pct,
        MAX(CASE WHEN rn = 2 THEN dunks_made END) AS h2_dunks_made,
        MAX(CASE WHEN rn = 2 THEN dunks_att END) AS h2_dunks_att,
        MAX(CASE WHEN rn = 2 THEN dunk_pct END) AS h2_dunk_pct,
        MAX(CASE WHEN rn = 2 THEN pick END) AS h2_pick,
        MAX(CASE WHEN rn = 2 THEN drtg END) AS h2_drtg,
        MAX(CASE WHEN rn = 2 THEN adrtg END) AS h2_adrtg,
        MAX(CASE WHEN rn = 2 THEN dporpag END) AS h2_dporpag,
        MAX(CASE WHEN rn = 2 THEN stops END) AS h2_stops,
        MAX(CASE WHEN rn = 2 THEN bpm END) AS h2_bpm,
        MAX(CASE WHEN rn = 2 THEN obpm END) AS h2_obpm,
        MAX(CASE WHEN rn = 2 THEN dbpm END) AS h2_dbpm,
        MAX(CASE WHEN rn = 2 THEN gbpm END) AS h2_gbpm,
        MAX(CASE WHEN rn = 2 THEN mp END) AS h2_mp,
        MAX(CASE WHEN rn = 2 THEN ogbpm END) AS h2_ogbpm,
        MAX(CASE WHEN rn = 2 THEN dgbpm END) AS h2_dgbpm,
        MAX(CASE WHEN rn = 2 THEN oreb END) AS h2_oreb,
        MAX(CASE WHEN rn = 2 THEN dreb END) AS h2_dreb,
        MAX(CASE WHEN rn = 2 THEN treb END) AS h2_treb,
        MAX(CASE WHEN rn = 2 THEN ast_raw END) AS h2_ast_raw,
        MAX(CASE WHEN rn = 2 THEN stl_raw END) AS h2_stl_raw,
        MAX(CASE WHEN rn = 2 THEN blk_raw END) AS h2_blk_raw,
        MAX(CASE WHEN rn = 2 THEN pts END) AS h2_pts,
        MAX(CASE WHEN rn = 2 THEN role END) AS h2_role,
        MAX(CASE WHEN rn = 2 THEN three_p_100 END) AS h2_three_p_100,
        MAX(CASE WHEN rn = 3 THEN player_id END) AS h3_player_id,
        MAX(CASE WHEN rn = 3 THEN player_name END) AS h3_player_name,
        MAX(CASE WHEN rn = 3 THEN team END) AS h3_team,
        MAX(CASE WHEN rn = 3 THEN conf END) AS h3_conf,
        MAX(CASE WHEN rn = 3 THEN gp END) AS h3_gp,
        MAX(CASE WHEN rn = 3 THEN min_pct END) AS h3_min_pct,
        MAX(CASE WHEN rn = 3 THEN ortg END) AS h3_ortg,
        MAX(CASE WHEN rn = 3 THEN usg END) AS h3_usg,
        MAX(CASE WHEN rn = 3 THEN efg END) AS h3_efg,
        MAX(CASE WHEN rn = 3 THEN ts END) AS h3_ts,
        MAX(CASE WHEN rn = 3 THEN orb END) AS h3_orb,
        MAX(CASE WHEN rn = 3 THEN drb END) AS h3_drb,
        MAX(CASE WHEN rn = 3 THEN ast END) AS h3_ast,
        MAX(CASE WHEN rn = 3 THEN tov END) AS h3_tov,
        MAX(CASE WHEN rn = 3 THEN ftm END) AS h3_ftm,
        MAX(CASE WHEN rn = 3 THEN fta END) AS h3_fta,
        MAX(CASE WHEN rn = 3 THEN ft_pct END) AS h3_ft_pct,
        MAX(CASE WHEN rn = 3 THEN two_pm END) AS h3_two_pm,
        MAX(CASE WHEN rn = 3 THEN two_pa END) AS h3_two_pa,
        MAX(CASE WHEN rn = 3 THEN two_p_pct END) AS h3_two_p_pct,
        MAX(CASE WHEN rn = 3 THEN tpm END) AS h3_tpm,
        MAX(CASE WHEN rn = 3 THEN tpa END) AS h3_tpa,
        MAX(CASE WHEN rn = 3 THEN tp_pct END) AS h3_tp_pct,
        MAX(CASE WHEN rn = 3 THEN blk END) AS h3_blk,
        MAX(CASE WHEN rn = 3 THEN stl END) AS h3_stl,
        MAX(CASE WHEN rn = 3 THEN ftr END) AS h3_ftr,
        MAX(CASE WHEN rn = 3 THEN yr END) AS h3_yr,
        MAX(CASE WHEN rn = 3 THEN ht END) AS h3_ht,
        MAX(CASE WHEN rn = 3 THEN num END) AS h3_num,
        MAX(CASE WHEN rn = 3 THEN porpag END) AS h3_porpag,
        MAX(CASE WHEN rn = 3 THEN adjoe END) AS h3_adjoe,
        MAX(CASE WHEN rn = 3 THEN pfr END) AS h3_pfr,
        MAX(CASE WHEN rn = 3 THEN season_year END) AS h3_season_year,
        MAX(CASE WHEN rn = 3 THEN pid END) AS h3_pid,
        MAX(CASE WHEN rn = 3 THEN type END) AS h3_type,
        MAX(CASE WHEN rn = 3 THEN rec_rank END) AS h3_rec_rank,
        MAX(CASE WHEN rn = 3 THEN ast_tov END) AS h3_ast_tov,
        MAX(CASE WHEN rn = 3 THEN rim_made END) AS h3_rim_made,
        MAX(CASE WHEN rn = 3 THEN rim_att END) AS h3_rim_att,
        MAX(CASE WHEN rn = 3 THEN mid_made END) AS h3_mid_made,
        MAX(CASE WHEN rn = 3 THEN mid_att END) AS h3_mid_att,
        MAX(CASE WHEN rn = 3 THEN rim_pct END) AS h3_rim_pct,
        MAX(CASE WHEN rn = 3 THEN mid_pct END) AS h3_mid_pct,
        MAX(CASE WHEN rn = 3 THEN dunks_made END) AS h3_dunks_made,
        MAX(CASE WHEN rn = 3 THEN dunks_att END) AS h3_dunks_att,
        MAX(CASE WHEN rn = 3 THEN dunk_pct END) AS h3_dunk_pct,
        MAX(CASE WHEN rn = 3 THEN pick END) AS h3_pick,
        MAX(CASE WHEN rn = 3 THEN drtg END) AS h3_drtg,
        MAX(CASE WHEN rn = 3 THEN adrtg END) AS h3_adrtg,
        MAX(CASE WHEN rn = 3 THEN dporpag END) AS h3_dporpag,
        MAX(CASE WHEN rn = 3 THEN stops END) AS h3_stops,
        MAX(CASE WHEN rn = 3 THEN bpm END) AS h3_bpm,
        MAX(CASE WHEN rn = 3 THEN obpm END) AS h3_obpm,
        MAX(CASE WHEN rn = 3 THEN dbpm END) AS h3_dbpm,
        MAX(CASE WHEN rn = 3 THEN gbpm END) AS h3_gbpm,
        MAX(CASE WHEN rn = 3 THEN mp END) AS h3_mp,
        MAX(CASE WHEN rn = 3 THEN ogbpm END) AS h3_ogbpm,
        MAX(CASE WHEN rn = 3 THEN dgbpm END) AS h3_dgbpm,
        MAX(CASE WHEN rn = 3 THEN oreb END) AS h3_oreb,
        MAX(CASE WHEN rn = 3 THEN dreb END) AS h3_dreb,
        MAX(CASE WHEN rn = 3 THEN treb END) AS h3_treb,
        MAX(CASE WHEN rn = 3 THEN ast_raw END) AS h3_ast_raw,
        MAX(CASE WHEN rn = 3 THEN stl_raw END) AS h3_stl_raw,
        MAX(CASE WHEN rn = 3 THEN blk_raw END) AS h3_blk_raw,
        MAX(CASE WHEN rn = 3 THEN pts END) AS h3_pts,
        MAX(CASE WHEN rn = 3 THEN role END) AS h3_role,
        MAX(CASE WHEN rn = 3 THEN three_p_100 END) AS h3_three_p_100,
        MAX(CASE WHEN rn = 4 THEN player_id END) AS h4_player_id,
        MAX(CASE WHEN rn = 4 THEN player_name END) AS h4_player_name,
        MAX(CASE WHEN rn = 4 THEN team END) AS h4_team,
        MAX(CASE WHEN rn = 4 THEN conf END) AS h4_conf,
        MAX(CASE WHEN rn = 4 THEN gp END) AS h4_gp,
        MAX(CASE WHEN rn = 4 THEN min_pct END) AS h4_min_pct,
        MAX(CASE WHEN rn = 4 THEN ortg END) AS h4_ortg,
        MAX(CASE WHEN rn = 4 THEN usg END) AS h4_usg,
        MAX(CASE WHEN rn = 4 THEN efg END) AS h4_efg,
        MAX(CASE WHEN rn = 4 THEN ts END) AS h4_ts,
        MAX(CASE WHEN rn = 4 THEN orb END) AS h4_orb,
        MAX(CASE WHEN rn = 4 THEN drb END) AS h4_drb,
        MAX(CASE WHEN rn = 4 THEN ast END) AS h4_ast,
        MAX(CASE WHEN rn = 4 THEN tov END) AS h4_tov,
        MAX(CASE WHEN rn = 4 THEN ftm END) AS h4_ftm,
        MAX(CASE WHEN rn = 4 THEN fta END) AS h4_fta,
        MAX(CASE WHEN rn = 4 THEN ft_pct END) AS h4_ft_pct,
        MAX(CASE WHEN rn = 4 THEN two_pm END) AS h4_two_pm,
        MAX(CASE WHEN rn = 4 THEN two_pa END) AS h4_two_pa,
        MAX(CASE WHEN rn = 4 THEN two_p_pct END) AS h4_two_p_pct,
        MAX(CASE WHEN rn = 4 THEN tpm END) AS h4_tpm,
        MAX(CASE WHEN rn = 4 THEN tpa END) AS h4_tpa,
        MAX(CASE WHEN rn = 4 THEN tp_pct END) AS h4_tp_pct,
        MAX(CASE WHEN rn = 4 THEN blk END) AS h4_blk,
        MAX(CASE WHEN rn = 4 THEN stl END) AS h4_stl,
        MAX(CASE WHEN rn = 4 THEN ftr END) AS h4_ftr,
        MAX(CASE WHEN rn = 4 THEN yr END) AS h4_yr,
        MAX(CASE WHEN rn = 4 THEN ht END) AS h4_ht,
        MAX(CASE WHEN rn = 4 THEN num END) AS h4_num,
        MAX(CASE WHEN rn = 4 THEN porpag END) AS h4_porpag,
        MAX(CASE WHEN rn = 4 THEN adjoe END) AS h4_adjoe,
        MAX(CASE WHEN rn = 4 THEN pfr END) AS h4_pfr,
        MAX(CASE WHEN rn = 4 THEN season_year END) AS h4_season_year,
        MAX(CASE WHEN rn = 4 THEN pid END) AS h4_pid,
        MAX(CASE WHEN rn = 4 THEN type END) AS h4_type,
        MAX(CASE WHEN rn = 4 THEN rec_rank END) AS h4_rec_rank,
        MAX(CASE WHEN rn = 4 THEN ast_tov END) AS h4_ast_tov,
        MAX(CASE WHEN rn = 4 THEN rim_made END) AS h4_rim_made,
        MAX(CASE WHEN rn = 4 THEN rim_att END) AS h4_rim_att,
        MAX(CASE WHEN rn = 4 THEN mid_made END) AS h4_mid_made,
        MAX(CASE WHEN rn = 4 THEN mid_att END) AS h4_mid_att,
        MAX(CASE WHEN rn = 4 THEN rim_pct END) AS h4_rim_pct,
        MAX(CASE WHEN rn = 4 THEN mid_pct END) AS h4_mid_pct,
        MAX(CASE WHEN rn = 4 THEN dunks_made END) AS h4_dunks_made,
        MAX(CASE WHEN rn = 4 THEN dunks_att END) AS h4_dunks_att,
        MAX(CASE WHEN rn = 4 THEN dunk_pct END) AS h4_dunk_pct,
        MAX(CASE WHEN rn = 4 THEN pick END) AS h4_pick,
        MAX(CASE WHEN rn = 4 THEN drtg END) AS h4_drtg,
        MAX(CASE WHEN rn = 4 THEN adrtg END) AS h4_adrtg,
        MAX(CASE WHEN rn = 4 THEN dporpag END) AS h4_dporpag,
        MAX(CASE WHEN rn = 4 THEN stops END) AS h4_stops,
        MAX(CASE WHEN rn = 4 THEN bpm END) AS h4_bpm,
        MAX(CASE WHEN rn = 4 THEN obpm END) AS h4_obpm,
        MAX(CASE WHEN rn = 4 THEN dbpm END) AS h4_dbpm,
        MAX(CASE WHEN rn = 4 THEN gbpm END) AS h4_gbpm,
        MAX(CASE WHEN rn = 4 THEN mp END) AS h4_mp,
        MAX(CASE WHEN rn = 4 THEN ogbpm END) AS h4_ogbpm,
        MAX(CASE WHEN rn = 4 THEN dgbpm END) AS h4_dgbpm,
        MAX(CASE WHEN rn = 4 THEN oreb END) AS h4_oreb,
        MAX(CASE WHEN rn = 4 THEN dreb END) AS h4_dreb,
        MAX(CASE WHEN rn = 4 THEN treb END) AS h4_treb,
        MAX(CASE WHEN rn = 4 THEN ast_raw END) AS h4_ast_raw,
        MAX(CASE WHEN rn = 4 THEN stl_raw END) AS h4_stl_raw,
        MAX(CASE WHEN rn = 4 THEN blk_raw END) AS h4_blk_raw,
        MAX(CASE WHEN rn = 4 THEN pts END) AS h4_pts,
        MAX(CASE WHEN rn = 4 THEN role END) AS h4_role,
        MAX(CASE WHEN rn = 4 THEN three_p_100 END) AS h4_three_p_100,
        MAX(CASE WHEN rn = 5 THEN player_id END) AS h5_player_id,
        MAX(CASE WHEN rn = 5 THEN player_name END) AS h5_player_name,
        MAX(CASE WHEN rn = 5 THEN team END) AS h5_team,
        MAX(CASE WHEN rn = 5 THEN conf END) AS h5_conf,
        MAX(CASE WHEN rn = 5 THEN gp END) AS h5_gp,
        MAX(CASE WHEN rn = 5 THEN min_pct END) AS h5_min_pct,
        MAX(CASE WHEN rn = 5 THEN ortg END) AS h5_ortg,
        MAX(CASE WHEN rn = 5 THEN usg END) AS h5_usg,
        MAX(CASE WHEN rn = 5 THEN efg END) AS h5_efg,
        MAX(CASE WHEN rn = 5 THEN ts END) AS h5_ts,
        MAX(CASE WHEN rn = 5 THEN orb END) AS h5_orb,
        MAX(CASE WHEN rn = 5 THEN drb END) AS h5_drb,
        MAX(CASE WHEN rn = 5 THEN ast END) AS h5_ast,
        MAX(CASE WHEN rn = 5 THEN tov END) AS h5_tov,
        MAX(CASE WHEN rn = 5 THEN ftm END) AS h5_ftm,
        MAX(CASE WHEN rn = 5 THEN fta END) AS h5_fta,
        MAX(CASE WHEN rn = 5 THEN ft_pct END) AS h5_ft_pct,
        MAX(CASE WHEN rn = 5 THEN two_pm END) AS h5_two_pm,
        MAX(CASE WHEN rn = 5 THEN two_pa END) AS h5_two_pa,
        MAX(CASE WHEN rn = 5 THEN two_p_pct END) AS h5_two_p_pct,
        MAX(CASE WHEN rn = 5 THEN tpm END) AS h5_tpm,
        MAX(CASE WHEN rn = 5 THEN tpa END) AS h5_tpa,
        MAX(CASE WHEN rn = 5 THEN tp_pct END) AS h5_tp_pct,
        MAX(CASE WHEN rn = 5 THEN blk END) AS h5_blk,
        MAX(CASE WHEN rn = 5 THEN stl END) AS h5_stl,
        MAX(CASE WHEN rn = 5 THEN ftr END) AS h5_ftr,
        MAX(CASE WHEN rn = 5 THEN yr END) AS h5_yr,
        MAX(CASE WHEN rn = 5 THEN ht END) AS h5_ht,
        MAX(CASE WHEN rn = 5 THEN num END) AS h5_num,
        MAX(CASE WHEN rn = 5 THEN porpag END) AS h5_porpag,
        MAX(CASE WHEN rn = 5 THEN adjoe END) AS h5_adjoe,
        MAX(CASE WHEN rn = 5 THEN pfr END) AS h5_pfr,
        MAX(CASE WHEN rn = 5 THEN season_year END) AS h5_season_year,
        MAX(CASE WHEN rn = 5 THEN pid END) AS h5_pid,
        MAX(CASE WHEN rn = 5 THEN type END) AS h5_type,
        MAX(CASE WHEN rn = 5 THEN rec_rank END) AS h5_rec_rank,
        MAX(CASE WHEN rn = 5 THEN ast_tov END) AS h5_ast_tov,
        MAX(CASE WHEN rn = 5 THEN rim_made END) AS h5_rim_made,
        MAX(CASE WHEN rn = 5 THEN rim_att END) AS h5_rim_att,
        MAX(CASE WHEN rn = 5 THEN mid_made END) AS h5_mid_made,
        MAX(CASE WHEN rn = 5 THEN mid_att END) AS h5_mid_att,
        MAX(CASE WHEN rn = 5 THEN rim_pct END) AS h5_rim_pct,
        MAX(CASE WHEN rn = 5 THEN mid_pct END) AS h5_mid_pct,
        MAX(CASE WHEN rn = 5 THEN dunks_made END) AS h5_dunks_made,
        MAX(CASE WHEN rn = 5 THEN dunks_att END) AS h5_dunks_att,
        MAX(CASE WHEN rn = 5 THEN dunk_pct END) AS h5_dunk_pct,
        MAX(CASE WHEN rn = 5 THEN pick END) AS h5_pick,
        MAX(CASE WHEN rn = 5 THEN drtg END) AS h5_drtg,
        MAX(CASE WHEN rn = 5 THEN adrtg END) AS h5_adrtg,
        MAX(CASE WHEN rn = 5 THEN dporpag END) AS h5_dporpag,
        MAX(CASE WHEN rn = 5 THEN stops END) AS h5_stops,
        MAX(CASE WHEN rn = 5 THEN bpm END) AS h5_bpm,
        MAX(CASE WHEN rn = 5 THEN obpm END) AS h5_obpm,
        MAX(CASE WHEN rn = 5 THEN dbpm END) AS h5_dbpm,
        MAX(CASE WHEN rn = 5 THEN gbpm END) AS h5_gbpm,
        MAX(CASE WHEN rn = 5 THEN mp END) AS h5_mp,
        MAX(CASE WHEN rn = 5 THEN ogbpm END) AS h5_ogbpm,
        MAX(CASE WHEN rn = 5 THEN dgbpm END) AS h5_dgbpm,
        MAX(CASE WHEN rn = 5 THEN oreb END) AS h5_oreb,
        MAX(CASE WHEN rn = 5 THEN dreb END) AS h5_dreb,
        MAX(CASE WHEN rn = 5 THEN treb END) AS h5_treb,
        MAX(CASE WHEN rn = 5 THEN ast_raw END) AS h5_ast_raw,
        MAX(CASE WHEN rn = 5 THEN stl_raw END) AS h5_stl_raw,
        MAX(CASE WHEN rn = 5 THEN blk_raw END) AS h5_blk_raw,
        MAX(CASE WHEN rn = 5 THEN pts END) AS h5_pts,
        MAX(CASE WHEN rn = 5 THEN role END) AS h5_role,
        MAX(CASE WHEN rn = 5 THEN three_p_100 END) AS h5_three_p_100
    FROM home_ranked
    GROUP BY game_id, lineup_id
),

joined AS (
SELECT
    ap.game_id,
    ap.game_date,
    ap.lineup_id,
    ap.net_pts,
    ap.poss,
    ap.net_eff,
    -- ap.a1_player_id,
    ap.a1_player_name,
    -- ap.a1_team,
    -- ap.a1_conf,
    -- ap.a1_gp,
    ap.a1_min_pct,
    ap.a1_ortg,
    ap.a1_usg,
    ap.a1_efg,
    ap.a1_ts,
    ap.a1_orb,
    ap.a1_drb,
    ap.a1_ast,
    ap.a1_tov,
    ap.a1_ftm,
    ap.a1_fta,
    ap.a1_ft_pct,
    ap.a1_two_pm,
    ap.a1_two_pa,
    ap.a1_two_p_pct,
    ap.a1_tpm,
    ap.a1_tpa,
    ap.a1_tp_pct,
    ap.a1_blk,
    ap.a1_stl,
    ap.a1_ftr,
    case when ap.a1_yr = 'Sr' then 4
    when ap.a1_yr = 'Jr' then 3
    when ap.a1_yr = 'So' then 2
    when ap.a1_yr = 'Fr' then 1
    end as a1_yr_num,
    CAST(SPLIT_PART(ap.a1_ht, '-', 1) AS INTEGER) * 12 + CAST(SPLIT_PART(ap.a1_ht, '-', 2) AS INTEGER) AS a1_ht_in,
    -- ap.a1_num,
    ap.a1_porpag,
    ap.a1_adjoe,
    ap.a1_pfr,
    -- ap.a1_season_year,
    -- ap.a1_pid,
    -- ap.a1_type,
    -- ap.a1_rec_rank,
    ap.a1_ast_tov,
    ap.a1_rim_made,
    ap.a1_rim_att,
    ap.a1_mid_made,
    ap.a1_mid_att,
    ap.a1_rim_pct,
    ap.a1_mid_pct,
    ap.a1_dunks_made,
    ap.a1_dunks_att,
    ap.a1_dunk_pct,
    -- ap.a1_pick,
    ap.a1_drtg,
    ap.a1_adrtg,
    ap.a1_dporpag,
    ap.a1_stops,
    ap.a1_bpm,
    ap.a1_obpm,
    ap.a1_dbpm,
    ap.a1_gbpm,
    ap.a1_mp,
    ap.a1_ogbpm,
    ap.a1_dgbpm,
    ap.a1_oreb,
    ap.a1_dreb,
    ap.a1_treb,
    ap.a1_ast_raw,
    ap.a1_stl_raw,
    ap.a1_blk_raw,
    ap.a1_pts,
    -- ap.a1_role,
    ap.a1_three_p_100,
    -- ap.a2_player_id,
    ap.a2_player_name,
    -- ap.a2_team,
    -- ap.a2_conf,
    -- ap.a2_gp,
    ap.a2_min_pct,
    ap.a2_ortg,
    ap.a2_usg,
    ap.a2_efg,
    ap.a2_ts,
    ap.a2_orb,
    ap.a2_drb,
    ap.a2_ast,
    ap.a2_tov,
    ap.a2_ftm,
    ap.a2_fta,
    ap.a2_ft_pct,
    ap.a2_two_pm,
    ap.a2_two_pa,
    ap.a2_two_p_pct,
    ap.a2_tpm,
    ap.a2_tpa,
    ap.a2_tp_pct,
    ap.a2_blk,
    ap.a2_stl,
    ap.a2_ftr,
    case when ap.a2_yr = 'Sr' then 4
    when ap.a2_yr = 'Jr' then 3
    when ap.a2_yr = 'So' then 2
    when ap.a2_yr = 'Fr' then 1
    end as a2_yr_num,
    CAST(SPLIT_PART(ap.a2_ht, '-', 1) AS INTEGER) * 12 + CAST(SPLIT_PART(ap.a2_ht, '-', 2) AS INTEGER) AS a2_ht_in,
    -- ap.a2_num,
    ap.a2_porpag,
    ap.a2_adjoe,
    ap.a2_pfr,
    -- ap.a2_season_year,
    -- ap.a2_pid,
    -- ap.a2_type,
    -- ap.a2_rec_rank,
    ap.a2_ast_tov,
    ap.a2_rim_made,
    ap.a2_rim_att,
    ap.a2_mid_made,
    ap.a2_mid_att,
    ap.a2_rim_pct,
    ap.a2_mid_pct,
    ap.a2_dunks_made,
    ap.a2_dunks_att,
    ap.a2_dunk_pct,
    -- ap.a2_pick,
    ap.a2_drtg,
    ap.a2_adrtg,
    ap.a2_dporpag,
    ap.a2_stops,
    ap.a2_bpm,
    ap.a2_obpm,
    ap.a2_dbpm,
    ap.a2_gbpm,
    ap.a2_mp,
    ap.a2_ogbpm,
    ap.a2_dgbpm,
    ap.a2_oreb,
    ap.a2_dreb,
    ap.a2_treb,
    ap.a2_ast_raw,
    ap.a2_stl_raw,
    ap.a2_blk_raw,
    ap.a2_pts,
    -- ap.a2_role,
    ap.a2_three_p_100,
    -- ap.a3_player_id,
    ap.a3_player_name,
    -- ap.a3_team,
    -- ap.a3_conf,
    -- ap.a3_gp,
    ap.a3_min_pct,
    ap.a3_ortg,
    ap.a3_usg,
    ap.a3_efg,
    ap.a3_ts,
    ap.a3_orb,
    ap.a3_drb,
    ap.a3_ast,
    ap.a3_tov,
    ap.a3_ftm,
    ap.a3_fta,
    ap.a3_ft_pct,
    ap.a3_two_pm,
    ap.a3_two_pa,
    ap.a3_two_p_pct,
    ap.a3_tpm,
    ap.a3_tpa,
    ap.a3_tp_pct,
    ap.a3_blk,
    ap.a3_stl,
    ap.a3_ftr,
    case when ap.a3_yr = 'Sr' then 4
    when ap.a3_yr = 'Jr' then 3
    when ap.a3_yr = 'So' then 2
    when ap.a3_yr = 'Fr' then 1
    end as a3_yr_num,
    CAST(SPLIT_PART(ap.a3_ht, '-', 1) AS INTEGER) * 12 + CAST(SPLIT_PART(ap.a3_ht, '-', 2) AS INTEGER) AS a3_ht_in,
    -- ap.a3_num,
    ap.a3_porpag,
    ap.a3_adjoe,
    ap.a3_pfr,
    -- ap.a3_season_year,
    -- ap.a3_pid,
    -- ap.a3_type,
    -- ap.a3_rec_rank,
    ap.a3_ast_tov,
    ap.a3_rim_made,
    ap.a3_rim_att,
    ap.a3_mid_made,
    ap.a3_mid_att,
    ap.a3_rim_pct,
    ap.a3_mid_pct,
    ap.a3_dunks_made,
    ap.a3_dunks_att,
    ap.a3_dunk_pct,
    -- ap.a3_pick,
    ap.a3_drtg,
    ap.a3_adrtg,
    ap.a3_dporpag,
    ap.a3_stops,
    ap.a3_bpm,
    ap.a3_obpm,
    ap.a3_dbpm,
    ap.a3_gbpm,
    ap.a3_mp,
    ap.a3_ogbpm,
    ap.a3_dgbpm,
    ap.a3_oreb,
    ap.a3_dreb,
    ap.a3_treb,
    ap.a3_ast_raw,
    ap.a3_stl_raw,
    ap.a3_blk_raw,
    ap.a3_pts,
    -- ap.a3_role,
    ap.a3_three_p_100,
    -- ap.a4_player_id,
    ap.a4_player_name,
    -- ap.a4_team,
    -- ap.a4_conf,
    -- ap.a4_gp,
    ap.a4_min_pct,
    ap.a4_ortg,
    ap.a4_usg,
    ap.a4_efg,
    ap.a4_ts,
    ap.a4_orb,
    ap.a4_drb,
    ap.a4_ast,
    ap.a4_tov,
    ap.a4_ftm,
    ap.a4_fta,
    ap.a4_ft_pct,
    ap.a4_two_pm,
    ap.a4_two_pa,
    ap.a4_two_p_pct,
    ap.a4_tpm,
    ap.a4_tpa,
    ap.a4_tp_pct,
    ap.a4_blk,
    ap.a4_stl,
    ap.a4_ftr,
    case when ap.a4_yr = 'Sr' then 4
    when ap.a4_yr = 'Jr' then 3
    when ap.a4_yr = 'So' then 2
    when ap.a4_yr = 'Fr' then 1
    end as a4_yr_num,
    CAST(SPLIT_PART(ap.a4_ht, '-', 1) AS INTEGER) * 12 + CAST(SPLIT_PART(ap.a4_ht, '-', 2) AS INTEGER) AS a4_ht_in,
    -- ap.a4_num,
    ap.a4_porpag,
    ap.a4_adjoe,
    ap.a4_pfr,
    -- ap.a4_season_year,
    -- ap.a4_pid,
    -- ap.a4_type,
    -- ap.a4_rec_rank,
    ap.a4_ast_tov,
    ap.a4_rim_made,
    ap.a4_rim_att,
    ap.a4_mid_made,
    ap.a4_mid_att,
    ap.a4_rim_pct,
    ap.a4_mid_pct,
    ap.a4_dunks_made,
    ap.a4_dunks_att,
    ap.a4_dunk_pct,
    -- ap.a4_pick,
    ap.a4_drtg,
    ap.a4_adrtg,
    ap.a4_dporpag,
    ap.a4_stops,
    ap.a4_bpm,
    ap.a4_obpm,
    ap.a4_dbpm,
    ap.a4_gbpm,
    ap.a4_mp,
    ap.a4_ogbpm,
    ap.a4_dgbpm,
    ap.a4_oreb,
    ap.a4_dreb,
    ap.a4_treb,
    ap.a4_ast_raw,
    ap.a4_stl_raw,
    ap.a4_blk_raw,
    ap.a4_pts,
    -- ap.a4_role,
    ap.a4_three_p_100,
    -- ap.a5_player_id,
    ap.a5_player_name,
    -- ap.a5_team,
    -- ap.a5_conf,
    -- ap.a5_gp,
    ap.a5_min_pct,
    ap.a5_ortg,
    ap.a5_usg,
    ap.a5_efg,
    ap.a5_ts,
    ap.a5_orb,
    ap.a5_drb,
    ap.a5_ast,
    ap.a5_tov,
    ap.a5_ftm,
    ap.a5_fta,
    ap.a5_ft_pct,
    ap.a5_two_pm,
    ap.a5_two_pa,
    ap.a5_two_p_pct,
    ap.a5_tpm,
    ap.a5_tpa,
    ap.a5_tp_pct,
    ap.a5_blk,
    ap.a5_stl,
    ap.a5_ftr,
    case when ap.a5_yr = 'Sr' then 4
    when ap.a5_yr = 'Jr' then 3
    when ap.a5_yr = 'So' then 2
    when ap.a5_yr = 'Fr' then 1
    end as a5_yr_num,
    CAST(SPLIT_PART(ap.a5_ht, '-', 1) AS INTEGER) * 12 + CAST(SPLIT_PART(ap.a5_ht, '-', 2) AS INTEGER) AS a5_ht_in,
    -- ap.a5_num,
    ap.a5_porpag,
    ap.a5_adjoe,
    ap.a5_pfr,
    -- ap.a5_season_year,
    -- ap.a5_pid,
    -- ap.a5_type,
    -- ap.a5_rec_rank,
    ap.a5_ast_tov,
    ap.a5_rim_made,
    ap.a5_rim_att,
    ap.a5_mid_made,
    ap.a5_mid_att,
    ap.a5_rim_pct,
    ap.a5_mid_pct,
    ap.a5_dunks_made,
    ap.a5_dunks_att,
    ap.a5_dunk_pct,
    -- ap.a5_pick,
    ap.a5_drtg,
    ap.a5_adrtg,
    ap.a5_dporpag,
    ap.a5_stops,
    ap.a5_bpm,
    ap.a5_obpm,
    ap.a5_dbpm,
    ap.a5_gbpm,
    ap.a5_mp,
    ap.a5_ogbpm,
    ap.a5_dgbpm,
    ap.a5_oreb,
    ap.a5_dreb,
    ap.a5_treb,
    ap.a5_ast_raw,
    ap.a5_stl_raw,
    ap.a5_blk_raw,
    ap.a5_pts,
    -- ap.a5_role,
    ap.a5_three_p_100,
    -- hp.h1_player_id,
    hp.h1_player_name,
    -- hp.h1_team,
    -- hp.h1_conf,
    -- hp.h1_gp,
    hp.h1_min_pct,
    hp.h1_ortg,
    hp.h1_usg,
    hp.h1_efg,
    hp.h1_ts,
    hp.h1_orb,
    hp.h1_drb,
    hp.h1_ast,
    hp.h1_tov,
    hp.h1_ftm,
    hp.h1_fta,
    hp.h1_ft_pct,
    hp.h1_two_pm,
    hp.h1_two_pa,
    hp.h1_two_p_pct,
    hp.h1_tpm,
    hp.h1_tpa,
    hp.h1_tp_pct,
    hp.h1_blk,
    hp.h1_stl,
    hp.h1_ftr,
    case when hp.h1_yr = 'Sr' then 4
    when hp.h1_yr = 'Jr' then 3
    when hp.h1_yr = 'So' then 2
    when hp.h1_yr = 'Fr' then 1
    end as h1_yr_num,
    CAST(SPLIT_PART(hp.h1_ht, '-', 1) AS INTEGER) * 12 + CAST(SPLIT_PART(hp.h1_ht, '-', 2) AS INTEGER) AS h1_ht_in,
    -- hp.h1_num,
    hp.h1_porpag,
    hp.h1_adjoe,
    hp.h1_pfr,
    -- hp.h1_season_year,
    -- hp.h1_pid,
    -- hp.h1_type,
    -- hp.h1_rec_rank,
    hp.h1_ast_tov,
    hp.h1_rim_made,
    hp.h1_rim_att,
    hp.h1_mid_made,
    hp.h1_mid_att,
    hp.h1_rim_pct,
    hp.h1_mid_pct,
    hp.h1_dunks_made,
    hp.h1_dunks_att,
    hp.h1_dunk_pct,
    -- hp.h1_pick,
    hp.h1_drtg,
    hp.h1_adrtg,
    hp.h1_dporpag,
    hp.h1_stops,
    hp.h1_bpm,
    hp.h1_obpm,
    hp.h1_dbpm,
    hp.h1_gbpm,
    hp.h1_mp,
    hp.h1_ogbpm,
    hp.h1_dgbpm,
    hp.h1_oreb,
    hp.h1_dreb,
    hp.h1_treb,
    hp.h1_ast_raw,
    hp.h1_stl_raw,
    hp.h1_blk_raw,
    hp.h1_pts,
    -- hp.h1_role,
    hp.h1_three_p_100,
    -- hp.h2_player_id,
    hp.h2_player_name,
    -- hp.h2_team,
    -- hp.h2_conf,
    -- hp.h2_gp,
    hp.h2_min_pct,
    hp.h2_ortg,
    hp.h2_usg,
    hp.h2_efg,
    hp.h2_ts,
    hp.h2_orb,
    hp.h2_drb,
    hp.h2_ast,
    hp.h2_tov,
    hp.h2_ftm,
    hp.h2_fta,
    hp.h2_ft_pct,
    hp.h2_two_pm,
    hp.h2_two_pa,
    hp.h2_two_p_pct,
    hp.h2_tpm,
    hp.h2_tpa,
    hp.h2_tp_pct,
    hp.h2_blk,
    hp.h2_stl,
    hp.h2_ftr,
    case when hp.h2_yr = 'Sr' then 4
    when hp.h2_yr = 'Jr' then 3
    when hp.h2_yr = 'So' then 2
    when hp.h2_yr = 'Fr' then 1
    end as h2_yr_num,
    CAST(SPLIT_PART(hp.h2_ht, '-', 1) AS INTEGER) * 12 + CAST(SPLIT_PART(hp.h2_ht, '-', 2) AS INTEGER) AS h2_ht_in,
    -- hp.h2_num,
    hp.h2_porpag,
    hp.h2_adjoe,
    hp.h2_pfr,
    -- hp.h2_season_year,
    -- hp.h2_pid,
    -- hp.h2_type,
    -- hp.h2_rec_rank,
    hp.h2_ast_tov,
    hp.h2_rim_made,
    hp.h2_rim_att,
    hp.h2_mid_made,
    hp.h2_mid_att,
    hp.h2_rim_pct,
    hp.h2_mid_pct,
    hp.h2_dunks_made,
    hp.h2_dunks_att,
    hp.h2_dunk_pct,
    -- hp.h2_pick,
    hp.h2_drtg,
    hp.h2_adrtg,
    hp.h2_dporpag,
    hp.h2_stops,
    hp.h2_bpm,
    hp.h2_obpm,
    hp.h2_dbpm,
    hp.h2_gbpm,
    hp.h2_mp,
    hp.h2_ogbpm,
    hp.h2_dgbpm,
    hp.h2_oreb,
    hp.h2_dreb,
    hp.h2_treb,
    hp.h2_ast_raw,
    hp.h2_stl_raw,
    hp.h2_blk_raw,
    hp.h2_pts,
    -- hp.h2_role,
    hp.h2_three_p_100,
    -- hp.h3_player_id,
    hp.h3_player_name,
    -- hp.h3_team,
    -- hp.h3_conf,
    -- hp.h3_gp,
    hp.h3_min_pct,
    hp.h3_ortg,
    hp.h3_usg,
    hp.h3_efg,
    hp.h3_ts,
    hp.h3_orb,
    hp.h3_drb,
    hp.h3_ast,
    hp.h3_tov,
    hp.h3_ftm,
    hp.h3_fta,
    hp.h3_ft_pct,
    hp.h3_two_pm,
    hp.h3_two_pa,
    hp.h3_two_p_pct,
    hp.h3_tpm,
    hp.h3_tpa,
    hp.h3_tp_pct,
    hp.h3_blk,
    hp.h3_stl,
    hp.h3_ftr,
    case when hp.h3_yr = 'Sr' then 4
    when hp.h3_yr = 'Jr' then 3
    when hp.h3_yr = 'So' then 2
    when hp.h3_yr = 'Fr' then 1
    end as h3_yr_num,
    CAST(SPLIT_PART(hp.h3_ht, '-', 1) AS INTEGER) * 12 + CAST(SPLIT_PART(hp.h3_ht, '-', 2) AS INTEGER) AS h3_ht_in,
    -- hp.h3_num,
    hp.h3_porpag,
    hp.h3_adjoe,
    hp.h3_pfr,
    -- hp.h3_season_year,
    -- hp.h3_pid,
    -- hp.h3_type,
    -- hp.h3_rec_rank,
    hp.h3_ast_tov,
    hp.h3_rim_made,
    hp.h3_rim_att,
    hp.h3_mid_made,
    hp.h3_mid_att,
    hp.h3_rim_pct,
    hp.h3_mid_pct,
    hp.h3_dunks_made,
    hp.h3_dunks_att,
    hp.h3_dunk_pct,
    -- hp.h3_pick,
    hp.h3_drtg,
    hp.h3_adrtg,
    hp.h3_dporpag,
    hp.h3_stops,
    hp.h3_bpm,
    hp.h3_obpm,
    hp.h3_dbpm,
    hp.h3_gbpm,
    hp.h3_mp,
    hp.h3_ogbpm,
    hp.h3_dgbpm,
    hp.h3_oreb,
    hp.h3_dreb,
    hp.h3_treb,
    hp.h3_ast_raw,
    hp.h3_stl_raw,
    hp.h3_blk_raw,
    hp.h3_pts,
    -- hp.h3_role,
    hp.h3_three_p_100,
    -- hp.h4_player_id,
    hp.h4_player_name,
    -- hp.h4_team,
    -- hp.h4_conf,
    -- hp.h4_gp,
    hp.h4_min_pct,
    hp.h4_ortg,
    hp.h4_usg,
    hp.h4_efg,
    hp.h4_ts,
    hp.h4_orb,
    hp.h4_drb,
    hp.h4_ast,
    hp.h4_tov,
    hp.h4_ftm,
    hp.h4_fta,
    hp.h4_ft_pct,
    hp.h4_two_pm,
    hp.h4_two_pa,
    hp.h4_two_p_pct,
    hp.h4_tpm,
    hp.h4_tpa,
    hp.h4_tp_pct,
    hp.h4_blk,
    hp.h4_stl,
    hp.h4_ftr,
    case when hp.h4_yr = 'Sr' then 4
    when hp.h4_yr = 'Jr' then 3
    when hp.h4_yr = 'So' then 2
    when hp.h4_yr = 'Fr' then 1
    end as h4_yr_num,
    CAST(SPLIT_PART(hp.h4_ht, '-', 1) AS INTEGER) * 12 + CAST(SPLIT_PART(hp.h4_ht, '-', 2) AS INTEGER) AS h4_ht_in,
    -- hp.h4_num,
    hp.h4_porpag,
    hp.h4_adjoe,
    hp.h4_pfr,
    -- hp.h4_season_year,
    -- hp.h4_pid,
    -- hp.h4_type,
    -- hp.h4_rec_rank,
    hp.h4_ast_tov,
    hp.h4_rim_made,
    hp.h4_rim_att,
    hp.h4_mid_made,
    hp.h4_mid_att,
    hp.h4_rim_pct,
    hp.h4_mid_pct,
    hp.h4_dunks_made,
    hp.h4_dunks_att,
    hp.h4_dunk_pct,
    -- hp.h4_pick,
    hp.h4_drtg,
    hp.h4_adrtg,
    hp.h4_dporpag,
    hp.h4_stops,
    hp.h4_bpm,
    hp.h4_obpm,
    hp.h4_dbpm,
    hp.h4_gbpm,
    hp.h4_mp,
    hp.h4_ogbpm,
    hp.h4_dgbpm,
    hp.h4_oreb,
    hp.h4_dreb,
    hp.h4_treb,
    hp.h4_ast_raw,
    hp.h4_stl_raw,
    hp.h4_blk_raw,
    hp.h4_pts,
    -- hp.h4_role,
    hp.h4_three_p_100,
    -- hp.h5_player_id,
    hp.h5_player_name,
    -- hp.h5_team,
    -- hp.h5_conf,
    -- hp.h5_gp,
    hp.h5_min_pct,
    hp.h5_ortg,
    hp.h5_usg,
    hp.h5_efg,
    hp.h5_ts,
    hp.h5_orb,
    hp.h5_drb,
    hp.h5_ast,
    hp.h5_tov,
    hp.h5_ftm,
    hp.h5_fta,
    hp.h5_ft_pct,
    hp.h5_two_pm,
    hp.h5_two_pa,
    hp.h5_two_p_pct,
    hp.h5_tpm,
    hp.h5_tpa,
    hp.h5_tp_pct,
    hp.h5_blk,
    hp.h5_stl,
    hp.h5_ftr,
    case when hp.h5_yr = 'Sr' then 4
    when hp.h5_yr = 'Jr' then 3
    when hp.h5_yr = 'So' then 2
    when hp.h5_yr = 'Fr' then 1
    end as h5_yr_num,
    CAST(SPLIT_PART(hp.h5_ht, '-', 1) AS INTEGER) * 12 + CAST(SPLIT_PART(hp.h5_ht, '-', 2) AS INTEGER) AS h5_ht_in,
    -- hp.h5_num,
    hp.h5_porpag,
    hp.h5_adjoe,
    hp.h5_pfr,
    -- hp.h5_season_year,
    -- hp.h5_pid,
    -- hp.h5_type,
    -- hp.h5_rec_rank,
    hp.h5_ast_tov,
    hp.h5_rim_made,
    hp.h5_rim_att,
    hp.h5_mid_made,
    hp.h5_mid_att,
    hp.h5_rim_pct,
    hp.h5_mid_pct,
    hp.h5_dunks_made,
    hp.h5_dunks_att,
    hp.h5_dunk_pct,
    -- hp.h5_pick,
    hp.h5_drtg,
    hp.h5_adrtg,
    hp.h5_dporpag,
    hp.h5_stops,
    hp.h5_bpm,
    hp.h5_obpm,
    hp.h5_dbpm,
    hp.h5_gbpm,
    hp.h5_mp,
    hp.h5_ogbpm,
    hp.h5_dgbpm,
    hp.h5_oreb,
    hp.h5_dreb,
    hp.h5_treb,
    hp.h5_ast_raw,
    hp.h5_stl_raw,
    hp.h5_blk_raw,
    hp.h5_pts,
    -- hp.h5_role,
    hp.h5_three_p_100
FROM away_pivoted ap
JOIN home_pivoted hp ON ap.game_id = hp.game_id AND ap.lineup_id = hp.lineup_id
),

aggs AS (
    SELECT *,
        -- Away averages
        (a1_ht_in + a2_ht_in + a3_ht_in + a4_ht_in + a5_ht_in) / 5.0 AS a_avg_ht,
        (a1_yr_num + a2_yr_num + a3_yr_num + a4_yr_num + a5_yr_num) / 5.0 AS a_avg_yr,
        (a1_ortg + a2_ortg + a3_ortg + a4_ortg + a5_ortg) / 5.0 AS a_avg_ortg,
        (a1_drtg + a2_drtg + a3_drtg + a4_drtg + a5_drtg) / 5.0 AS a_avg_drtg,
        (a1_ts   + a2_ts   + a3_ts   + a4_ts   + a5_ts  ) / 5.0 AS a_avg_ts,
        (a1_tov  + a2_tov  + a3_tov  + a4_tov  + a5_tov ) / 5.0 AS a_avg_tov,
        (a1_orb  + a2_orb  + a3_orb  + a4_orb  + a5_orb ) / 5.0 AS a_avg_orb,
        (a1_drb  + a2_drb  + a3_drb  + a4_drb  + a5_drb ) / 5.0 AS a_avg_drb,
        (a1_ast  + a2_ast  + a3_ast  + a4_ast  + a5_ast ) / 5.0 AS a_avg_ast,
        (a1_blk  + a2_blk  + a3_blk  + a4_blk  + a5_blk ) / 5.0 AS a_avg_blk,
        (a1_stl  + a2_stl  + a3_stl  + a4_stl  + a5_stl ) / 5.0 AS a_avg_stl,
        (a1_bpm  + a2_bpm  + a3_bpm  + a4_bpm  + a5_bpm ) / 5.0 AS a_avg_bpm,
        -- Away derived
        ((a1_ortg + a2_ortg + a3_ortg + a4_ortg + a5_ortg) - (a1_drtg + a2_drtg + a3_drtg + a4_drtg + a5_drtg)) / 5.0 AS a_net_rating,
        ((a1_ast  + a2_ast  + a3_ast  + a4_ast  + a5_ast ) - (a1_tov  + a2_tov  + a3_tov  + a4_tov  + a5_tov )) / 5.0 AS a_playmaking,
        (a1_blk  + a2_blk  + a3_blk  + a4_blk  + a5_blk ) / 5.0 + (a1_drb + a2_drb + a3_drb + a4_drb + a5_drb) / 5.0 AS a_interior_defense,
        (a1_stl  + a2_stl  + a3_stl  + a4_stl  + a5_stl ) / 5.0 AS a_perimeter_defense,
        (a1_usg * a1_ts + a2_usg * a2_ts + a3_usg * a3_ts + a4_usg * a4_ts + a5_usg * a5_ts) / NULLIF(a1_usg + a2_usg + a3_usg + a4_usg + a5_usg, 0) AS a_wtd_ts,
        (
            CASE WHEN a1_tpa / NULLIF(CAST(a1_tpa + a1_two_pa AS DOUBLE), 0) > 0.30 THEN 1.0 ELSE 0.0 END +
            CASE WHEN a2_tpa / NULLIF(CAST(a2_tpa + a2_two_pa AS DOUBLE), 0) > 0.30 THEN 1.0 ELSE 0.0 END +
            CASE WHEN a3_tpa / NULLIF(CAST(a3_tpa + a3_two_pa AS DOUBLE), 0) > 0.30 THEN 1.0 ELSE 0.0 END +
            CASE WHEN a4_tpa / NULLIF(CAST(a4_tpa + a4_two_pa AS DOUBLE), 0) > 0.30 THEN 1.0 ELSE 0.0 END +
            CASE WHEN a5_tpa / NULLIF(CAST(a5_tpa + a5_two_pa AS DOUBLE), 0) > 0.30 THEN 1.0 ELSE 0.0 END
        ) / 5.0 AS a_spacing_score,
        (
            a1_tpa / NULLIF(CAST(a1_tpa + a1_two_pa AS DOUBLE), 0) * a1_tp_pct +
            a2_tpa / NULLIF(CAST(a2_tpa + a2_two_pa AS DOUBLE), 0) * a2_tp_pct +
            a3_tpa / NULLIF(CAST(a3_tpa + a3_two_pa AS DOUBLE), 0) * a3_tp_pct +
            a4_tpa / NULLIF(CAST(a4_tpa + a4_two_pa AS DOUBLE), 0) * a4_tp_pct +
            a5_tpa / NULLIF(CAST(a5_tpa + a5_two_pa AS DOUBLE), 0) * a5_tp_pct
        ) / NULLIF(
            a1_tpa / NULLIF(CAST(a1_tpa + a1_two_pa AS DOUBLE), 0) +
            a2_tpa / NULLIF(CAST(a2_tpa + a2_two_pa AS DOUBLE), 0) +
            a3_tpa / NULLIF(CAST(a3_tpa + a3_two_pa AS DOUBLE), 0) +
            a4_tpa / NULLIF(CAST(a4_tpa + a4_two_pa AS DOUBLE), 0) +
            a5_tpa / NULLIF(CAST(a5_tpa + a5_two_pa AS DOUBLE), 0),
        0) AS a_perimeter_threat,

        -- Home averages
        (h1_ht_in + h2_ht_in + h3_ht_in + h4_ht_in + h5_ht_in) / 5.0 AS h_avg_ht,
        (h1_yr_num + h2_yr_num + h3_yr_num + h4_yr_num + h5_yr_num) / 5.0 AS h_avg_yr,
        (h1_ortg + h2_ortg + h3_ortg + h4_ortg + h5_ortg) / 5.0 AS h_avg_ortg,
        (h1_drtg + h2_drtg + h3_drtg + h4_drtg + h5_drtg) / 5.0 AS h_avg_drtg,
        (h1_ts   + h2_ts   + h3_ts   + h4_ts   + h5_ts  ) / 5.0 AS h_avg_ts,
        (h1_tov  + h2_tov  + h3_tov  + h4_tov  + h5_tov ) / 5.0 AS h_avg_tov,
        (h1_orb  + h2_orb  + h3_orb  + h4_orb  + h5_orb ) / 5.0 AS h_avg_orb,
        (h1_drb  + h2_drb  + h3_drb  + h4_drb  + h5_drb ) / 5.0 AS h_avg_drb,
        (h1_ast  + h2_ast  + h3_ast  + h4_ast  + h5_ast ) / 5.0 AS h_avg_ast,
        (h1_blk  + h2_blk  + h3_blk  + h4_blk  + h5_blk ) / 5.0 AS h_avg_blk,
        (h1_stl  + h2_stl  + h3_stl  + h4_stl  + h5_stl ) / 5.0 AS h_avg_stl,
        (h1_bpm  + h2_bpm  + h3_bpm  + h4_bpm  + h5_bpm ) / 5.0 AS h_avg_bpm,
        -- Home derived
        ((h1_ortg + h2_ortg + h3_ortg + h4_ortg + h5_ortg) - (h1_drtg + h2_drtg + h3_drtg + h4_drtg + h5_drtg)) / 5.0 AS h_net_rating,
        ((h1_ast  + h2_ast  + h3_ast  + h4_ast  + h5_ast ) - (h1_tov  + h2_tov  + h3_tov  + h4_tov  + h5_tov )) / 5.0 AS h_playmaking,
        (h1_blk  + h2_blk  + h3_blk  + h4_blk  + h5_blk ) / 5.0 + (h1_drb + h2_drb + h3_drb + h4_drb + h5_drb) / 5.0 AS h_interior_defense,
        (h1_stl  + h2_stl  + h3_stl  + h4_stl  + h5_stl ) / 5.0 AS h_perimeter_defense,
        (h1_usg * h1_ts + h2_usg * h2_ts + h3_usg * h3_ts + h4_usg * h4_ts + h5_usg * h5_ts) / NULLIF(h1_usg + h2_usg + h3_usg + h4_usg + h5_usg, 0) AS h_wtd_ts,
        (
            CASE WHEN h1_tpa / NULLIF(CAST(h1_tpa + h1_two_pa AS DOUBLE), 0) > 0.30 THEN 1.0 ELSE 0.0 END +
            CASE WHEN h2_tpa / NULLIF(CAST(h2_tpa + h2_two_pa AS DOUBLE), 0) > 0.30 THEN 1.0 ELSE 0.0 END +
            CASE WHEN h3_tpa / NULLIF(CAST(h3_tpa + h3_two_pa AS DOUBLE), 0) > 0.30 THEN 1.0 ELSE 0.0 END +
            CASE WHEN h4_tpa / NULLIF(CAST(h4_tpa + h4_two_pa AS DOUBLE), 0) > 0.30 THEN 1.0 ELSE 0.0 END +
            CASE WHEN h5_tpa / NULLIF(CAST(h5_tpa + h5_two_pa AS DOUBLE), 0) > 0.30 THEN 1.0 ELSE 0.0 END
        ) / 5.0 AS h_spacing_score,
        (
            h1_tpa / NULLIF(CAST(h1_tpa + h1_two_pa AS DOUBLE), 0) * h1_tp_pct +
            h2_tpa / NULLIF(CAST(h2_tpa + h2_two_pa AS DOUBLE), 0) * h2_tp_pct +
            h3_tpa / NULLIF(CAST(h3_tpa + h3_two_pa AS DOUBLE), 0) * h3_tp_pct +
            h4_tpa / NULLIF(CAST(h4_tpa + h4_two_pa AS DOUBLE), 0) * h4_tp_pct +
            h5_tpa / NULLIF(CAST(h5_tpa + h5_two_pa AS DOUBLE), 0) * h5_tp_pct
        ) / NULLIF(
            h1_tpa / NULLIF(CAST(h1_tpa + h1_two_pa AS DOUBLE), 0) +
            h2_tpa / NULLIF(CAST(h2_tpa + h2_two_pa AS DOUBLE), 0) +
            h3_tpa / NULLIF(CAST(h3_tpa + h3_two_pa AS DOUBLE), 0) +
            h4_tpa / NULLIF(CAST(h4_tpa + h4_two_pa AS DOUBLE), 0) +
            h5_tpa / NULLIF(CAST(h5_tpa + h5_two_pa AS DOUBLE), 0),
        0) AS h_perimeter_threat,
    FROM joined
)

SELECT *,
    -- Cross-lineup interactions
    a_avg_ht - h_avg_ht                        AS ht_delta,
    a_avg_yr - h_avg_yr                        AS yr_delta,
    a_avg_ortg - h_avg_ortg                    AS off_delta,
    h_avg_drtg - a_avg_drtg                    AS def_delta,
    a_net_rating - h_net_rating                AS net_rating_delta,
    h_avg_drb   - a_avg_orb                    AS reb_battle,
    a_spacing_score - h_spacing_score          AS spacing_mismatch,
    a_playmaking - h_playmaking                AS playmaking_delta,
    a_interior_defense - h_interior_defense    AS interior_delta,
    a_perimeter_defense - h_perimeter_defense  AS perimeter_defense_delta,
    a_avg_bpm - h_avg_bpm                      AS bpm_delta
FROM aggs
